### ISSUE TITLE
watsonへ文章を渡す際に十分な単語数が必要

### ISSUE THREAD

**Issue by shinji19** [antexe/nickname#19]
なお日本語テキストの場合、動作するためには最低でも 70 単語が必要で、ある程度の精度を求めるには 3,500 単語以上、一般的には 6,000 単語以上必要である、とのことです（という警告メッセージがアウトプットされた JSON テキストの中に書かれています）。なので、例えばメールにしても１回に送信するメールの中身だけだと、動くことは動くが、あまり精度の高い結果にはならないことが予想されます。アプリケーションとして実装するには、それなりの量のインプットデータを入手する仕組みと併せて実装する必要があるように思えます。
http://dotnsf.blog.jp/tag/insights

70単語だとエラーになるのでちゃんとハンドリングする。

**Comment by FujikawaKei** [comment]
- [ ] Tweet取得の時にとってくるtweet数を指定できるか確認
- [ ] メンションや日付など、不要なテキストはカットする

以上がタスクとしてありそう.

**Comment by takuyama29** [comment]
`70単語だとエラーになるのでちゃんとハンドリングする。` これは必須ですね。
あと前に発覚した、①鍵をかけているユーザーの場合 と ②ユーザーIDが正しくない場合? のエラーハンドリングも一緒にやる感じだよね。これは @FujikawaKei にお願いしても大丈夫なものかな？

> Tweet取得の時にとってくるtweet数を指定できるか確認

[Twitter REST APIの使い方](https://syncer.jp/Web/API/Twitter/REST_API/)に参考情報が書いてありました。
```
下記のURLに、GETメソッドでリクエストを送ります。
https://api.twitter.com/1.1/statuses/user_timeline.json

また、オプションとして、下記パラメータを指定します。
screen_name
スクリーンネーム。
count
取得件数。
```
取得数に関しては、多いに越したことは無いから特に指定しなくてもよいと思うのだけど、どうだろうか？

> メンションや日付など、不要なテキストはカットする

これあったら嬉しい、、！

> ある程度の精度を求めるには 3,500 単語以上、一般的には 6,000 単語以上必要である、とのことです

今回のあだ名命名のロジックは、ツイート内容との整合性とか、個人の正確の精度が低くてもある程度よしなにあだ名を作ってくれてるから、最初のリリースではWatson自体の性格分析の精度はそこまで高くなくても大丈夫だと思う。が、どうだだろう？ @shinji19

**Comment by FujikawaKei** [comment]
エラーハンドリングというか、エラーにならないように #26 で、鍵かかってないか、ユーザー名が存在するか、を確認するので、それは僕がやります。できそうだったら不要なテキストカットと分量増やすやつもやります。メンドくさそうだったらスルーします👍

**Comment by FujikawaKei** [comment]
#25 だった。

**Comment by takuyama29** [comment]
> エラーハンドリングというか、エラーにならないように #26 で、鍵かかってないか、ユーザー名が存在するか、を確認するので、それは僕がやります。できそうだったら不要なテキストカットと分量増やすやつもやります。メンドくさそうだったらスルーします👍

了解です！
お願いしますm(_ _)m

**Comment by shinji19** [comment]
https://github.com/antexe/nickname/pull/31/files
